#!/usr/bin/env node
// Fit Strategy A's remaining-rise / remaining-fall bound tables from historical
// (observation-at-local-hour -> final-CLI-extremum) pairs, then (with --write) regenerate
// netlify/functions/lib/diurnal_bounds.js. The bound per hour is a SAFE UPPER ENVELOPE
// (high quantile + buffer) of how much the extremum still moved after that hour, so a
// lock-in "certain win" almost never loses. The report shows the coverage/frequency
// tradeoff (a wider bound is safer but admits fewer lock-ins).
//
// Data sources (either works; fields are matched flexibly):
//   SNAPSHOTS=<market_logger export>  — rows {variable, localHour, maxSoFar|minSoFar, settle:{extremumF}}
//   SNAPSHOTS=</api/snapshots export> — rows {maxSoFar, actualHigh, hrsToPeak|localHour|ts+tz, ...}
// Usage:
//   node fit_diurnal.mjs --synthetic            # self-test: recover a known envelope
//   SNAPSHOTS=snaps.json node fit_diurnal.mjs   # report fitted tables (dry run)
//   SNAPSHOTS=snaps.json node fit_diurnal.mjs --write   # also overwrite diurnal_bounds.js

import { readFileSync, writeFileSync } from "node:fs";

const QUANTILE = Number(process.env.QUANTILE ?? 0.995); // coverage target for the bound
const BUFFER_F = Number(process.env.BUFFER_F ?? 1.0);   // extra °F on top of the quantile

const hourFromTs = (ts, tz) => { try {
  return parseInt(new Intl.DateTimeFormat("en-US", { timeZone: tz || "UTC", hour: "2-digit", hour12: false }).format(new Date(ts)), 10) % 24;
} catch { return null; } };

// Normalize any input record into {variable, h, remaining} triples (remaining >= 0).
function triples(records) {
  const out = [];
  const push = (variable, h, remaining) => { if (h != null && Number.isFinite(remaining)) out.push({ variable, h, remaining: Math.max(0, remaining) }); };
  for (const r of records) {
    const hHigh = r.localHour ?? (r.hrsToPeak != null ? Math.round(15 - r.hrsToPeak) : hourFromTs(r.ts, r.tz));
    const hLow  = r.localHour ?? (r.hrsToTrough != null ? Math.round(6 - r.hrsToTrough) : hourFromTs(r.ts, r.tz));
    const obsHigh = r.maxSoFar ?? r.maxSoFarCli;
    const obsLow  = r.minSoFar ?? r.minSoFarCli;
    const finHigh = (r.settle && r.variable === "high" ? r.settle.extremumF : undefined) ?? r.actualHigh ?? r.cliMaxF;
    const finLow  = (r.settle && r.variable === "low"  ? r.settle.extremumF : undefined) ?? r.actualLow ?? r.cliMinF;
    if ((r.variable === "high" || r.variable == null) && obsHigh != null && finHigh != null) push("high", hHigh, finHigh - obsHigh);
    if ((r.variable === "low"  || r.variable == null) && obsLow  != null && finLow  != null) push("low",  hLow,  obsLow - finLow);
  }
  return out;
}

const quantile = (xs, q) => { if (!xs.length) return null; const s = [...xs].sort((a, b) => a - b);
  return s[Math.min(s.length - 1, Math.floor(q * (s.length - 1)))]; };

// Fit one side into an hourly bound with monotone-non-increasing enforcement (a later hour's
// bound can't exceed an earlier hour's), then collapse to a compact {ltHour,val} table.
function fitSide(rows) {
  const byHour = {};
  for (const t of rows) (byHour[t.h] ??= []).push(t.remaining);
  const hours = Object.keys(byHour).map(Number).sort((a, b) => a - b);
  if (!hours.length) return { table: null, n: 0 };
  const raw = {};
  for (const h of hours) raw[h] = Math.ceil(quantile(byHour[h], QUANTILE) + BUFFER_F);
  // enforce monotone non-increasing over 0..23, carrying the widest (earliest) bound forward
  // into gaps and never letting a later hour exceed an earlier one.
  let cur = Math.max(...Object.values(raw), 1);
  const perHour = [];
  for (let h = 0; h <= 23; h++) { if (raw[h] != null) cur = Math.min(cur, raw[h]); perHour.push(cur); }
  // collapse consecutive equal values into {ltHour,val}
  const table = [];
  for (let h = 1; h <= 24; h++) if (h === 24 || perHour[h] !== perHour[h - 1])
    table.push({ ltHour: h === 24 ? Infinity : h, val: perHour[h - 1] });
  return { table, n: rows.length, byHour: Object.fromEntries(hours.map(h => [h, { n: byHour[h].length, boundF: raw[h] }])) };
}

function coverage(rows, table) { // fraction of history the fitted bound would have covered
  if (!rows.length) return null;
  const bound = (h) => (table.find(e => h < e.ltHour) || table[table.length - 1]).val;
  return rows.filter(t => t.remaining <= bound(t.h)).length / rows.length;
}

function serialize(rise, fall, n) {
  const t = (arr) => "[\n" + arr.map(e => `  { ltHour: ${e.ltHour === Infinity ? "Infinity" : e.ltHour}, val: ${e.val} },`).join("\n") + "\n]";
  return `// Remaining diurnal-change bound tables for Strategy A (see diurnal.js).
// GENERATED by fit_diurnal.mjs from ${n} historical (obs@hour -> final-CLI) pairs.
// Regenerate:  node fit_diurnal.mjs --write SNAPSHOTS=<export.json>
export const meta = { source: "fit_diurnal.mjs", fittedAt: ${JSON.stringify(new Date().toISOString())}, n: ${n}, quantile: ${QUANTILE}, bufferF: ${BUFFER_F} };
export const RISE = ${t(rise)};
export const FALL = ${t(fall)};
`;
}

// ---- synthetic self-test: known envelope, verify the fitter recovers a safe cover ----
function synthetic() {
  const recs = [];
  // remaining rise shrinks with hour; deterministic spread (no RNG)
  for (let h = 8; h <= 20; h++) for (let k = 0; k < 50; k++) {
    const maxPossible = Math.max(0, 26 - 1.6 * h);           // envelope we hope to recover
    const remaining = maxPossible * (k / 60);                 // 0..~83% of envelope
    recs.push({ variable: "high", localHour: h, maxSoFar: 80, settle: { extremumF: 80 + remaining } });
    recs.push({ variable: "low",  localHour: h, minSoFar: 50, settle: { extremumF: 50 - remaining * 0.7 } });
  }
  return recs;
}

const useSyn = process.argv.includes("--synthetic") || !process.env.SNAPSHOTS;
const records = useSyn ? synthetic() : JSON.parse(readFileSync(process.env.SNAPSHOTS, "utf8")).records
  ?? JSON.parse(readFileSync(process.env.SNAPSHOTS, "utf8"));
const tr = triples(Array.isArray(records) ? records : []);
const high = tr.filter(t => t.variable === "high"), low = tr.filter(t => t.variable === "low");
console.log(`${useSyn ? "SYNTHETIC self-test" : process.env.SNAPSHOTS}: ${tr.length} triples (${high.length} high, ${low.length} low), quantile=${QUANTILE}, buffer=${BUFFER_F}°F`);

const fRise = fitSide(high), fFall = fitSide(low);
if (!fRise.table || !fFall.table) { console.error("Not enough data for one side — need obs + final for both HIGH and LOW."); process.exit(2); }
console.log("\nRISE table:", JSON.stringify(fRise.table));
console.log("  coverage:", (100 * coverage(high, fRise.table)).toFixed(2) + "% of high days the bound would have held");
console.log("FALL table:", JSON.stringify(fFall.table));
console.log("  coverage:", (100 * coverage(low, fFall.table)).toFixed(2) + "% of low days the bound would have held");
console.log("\nPer-hour (high): n and fitted bound °F:", JSON.stringify(fRise.byHour));

if (process.argv.includes("--write")) {
  if (useSyn) { console.error("\nRefusing to --write from synthetic data. Provide SNAPSHOTS=<real export>."); process.exit(2); }
  writeFileSync("netlify/functions/lib/diurnal_bounds.js", serialize(fRise.table, fFall.table, tr.length));
  console.log("\n✓ wrote netlify/functions/lib/diurnal_bounds.js");
} else {
  console.log("\n(dry run — add --write with real SNAPSHOTS to regenerate diurnal_bounds.js)");
}
